#!/bin/bash
# Sync iCloud FLEET INBOX.md into the dashboard repo so the remote
# fleet-daily-review routine (which cannot reach iCloud) can read it.
#
# Runs daily at 08:45 BST via launchd — about 25 min before the remote
# routine fires at 09:08 UTC, giving CF + Anthropic time to see the
# fresh commit.
#
# Idempotent: only commits + pushes if the content actually changed.

set -e

SRC="$HOME/Library/Mobile Documents/com~apple~CloudDocs/claude/astro/FLEET/INBOX.md"
DST="$HOME/rank4ai-dashboard/FLEET_INBOX.md"
LOG="/tmp/rank4ai_fleet_inbox_sync.log"

echo "=== $(date -Iseconds) — fleet inbox sync ===" >> "$LOG"

if [ ! -f "$SRC" ]; then
  echo "  SRC missing: $SRC" >> "$LOG"
  exit 1
fi

# Read the source FIRST. In a launchd context macOS TCC frequently blocks
# iCloud reads ("Operation not permitted"); if that happens, bail BEFORE
# touching DST so a failed/empty read can never truncate the synced copy.
# (It did exactly that 8-12 Jun 2026, blanking FLEET_INBOX.md to 2 lines.)
SRC_CONTENT=$(/bin/cat "$SRC" 2>>"$LOG") || true
if [ -z "$SRC_CONTENT" ]; then
  echo "  ERROR: SRC unreadable or empty (TCC? grant Full Disk Access to the launchd shell). DST left intact." >> "$LOG"
  exit 1
fi

# Skip if unchanged (compare body, ignoring our timestamped header line)
if [ -f "$DST" ]; then
  DST_BODY=$(/usr/bin/tail -n +3 "$DST")
  if [ "$DST_BODY" = "$SRC_CONTENT" ]; then
    echo "  unchanged, skipping" >> "$LOG"
    exit 0
  fi
fi

# Wrap with a header so the remote agent knows the freshness
{
  echo "<!-- Synced from iCloud/claude/astro/FLEET/INBOX.md at $(date -Iseconds) by sync_fleet_inbox.sh. DO NOT EDIT this file directly — edit the iCloud source. -->"
  echo ""
  printf '%s\n' "$SRC_CONTENT"
} > "$DST"

cd "$HOME/rank4ai-dashboard" || exit 1
if /usr/bin/git status --porcelain FLEET_INBOX.md | /usr/bin/grep -q .; then
  /usr/bin/git add FLEET_INBOX.md
  /usr/bin/git commit -m "Sync FLEET INBOX from iCloud ($(date '+%Y-%m-%d %H:%M'))" >> "$LOG" 2>&1
  /usr/bin/git push origin main >> "$LOG" 2>&1
  echo "  synced + pushed" >> "$LOG"
else
  echo "  no diff after copy (unusual, content matches)" >> "$LOG"
fi
