#!/bin/bash
# Sync iCloud FLEET INBOX.md into the dashboard repo so the remote
# fleet-daily-review routine (which cannot reach iCloud) can read it.
#
# Runs daily at 08:45 BST via launchd — about 25 min before the remote
# routine fires at 09:08 UTC, giving CF + Anthropic time to see the
# fresh commit.
#
# Idempotent: only commits + pushes if the content actually changed.

set -e

SRC="$HOME/Library/Mobile Documents/com~apple~CloudDocs/claude/astro/FLEET/INBOX.md"
DST="$HOME/rank4ai-dashboard/FLEET_INBOX.md"
LOG="/tmp/rank4ai_fleet_inbox_sync.log"

echo "=== $(date -Iseconds) — fleet inbox sync ===" >> "$LOG"

if [ ! -f "$SRC" ]; then
  echo "  SRC missing: $SRC" >> "$LOG"
  exit 1
fi

# Compare hashes before copying
SRC_HASH=$(/usr/bin/shasum "$SRC" | /usr/bin/awk '{print $1}')
DST_HASH=""
if [ -f "$DST" ]; then
  DST_HASH=$(/usr/bin/shasum "$DST" | /usr/bin/awk '{print $1}')
fi

if [ "$SRC_HASH" = "$DST_HASH" ]; then
  echo "  unchanged, skipping" >> "$LOG"
  exit 0
fi

# Wrap with a header so the remote agent knows the freshness
{
  echo "<!-- Synced from iCloud/claude/astro/FLEET/INBOX.md at $(date -Iseconds) by sync_fleet_inbox.sh. DO NOT EDIT this file directly — edit the iCloud source. -->"
  echo ""
  cat "$SRC"
} > "$DST"

cd "$HOME/rank4ai-dashboard" || exit 1
if /usr/bin/git status --porcelain FLEET_INBOX.md | /usr/bin/grep -q .; then
  /usr/bin/git add FLEET_INBOX.md
  /usr/bin/git commit -m "Sync FLEET INBOX from iCloud ($(date '+%Y-%m-%d %H:%M'))" >> "$LOG" 2>&1
  /usr/bin/git push origin main >> "$LOG" 2>&1
  echo "  synced + pushed" >> "$LOG"
else
  echo "  no diff after copy (unusual, content matches)" >> "$LOG"
fi
